name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build APK with Buildozer
      uses: https://github.com/akshayaurora/action-buildozer@master
      with:
        workdir: .
        buildozer_version: master

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Jerry-AI-APK
        path: bin/*.apk
        
